import React from 'react';
import { HardDrive, Laptop, Moon, Package, ShieldCheck, Smartphone, Sun, Upload } from 'lucide-react';
import { Button, Card } from './ui';

export function SettingsScreen({ app, header }) {
  const themes = [{value:'light',label:'Claro',Icon:Sun},{value:'dark',label:'Escuro',Icon:Moon},{value:'system',label:'Sistema',Icon:Laptop}];
  return <div className="pb-12">{header('Configurações')}<div className="grid gap-5 lg:grid-cols-2">
    <Card className="p-5 lg:col-span-2"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-700 text-lg font-black text-white">{app.user.displayName?.[0]||'V'}</div><div className="min-w-0"><p className="truncate font-black">{app.isGuest?'Modo visitante':app.user.displayName || 'Minha conta'}</p><p className="truncate text-sm text-slate-500">{app.isGuest?'Dados locais neste dispositivo':app.user.email}</p></div></div>{!app.isGuest && app.user.email && !app.user.emailVerified && <div className="mt-4 flex flex-col gap-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200 sm:flex-row sm:items-center sm:justify-between"><span>Confirme seu e-mail para manter a conta protegida.</span><button onClick={app.resendVerification} className="font-black underline underline-offset-4">Reenviar confirmação</button></div>}{app.authNotice&&<p className="mt-3 rounded-xl bg-teal-50 p-3 text-sm text-teal-800 dark:bg-teal-950/30 dark:text-teal-200">{app.authNotice}</p>}{app.authError&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-200">{app.authError}</p>}</Card>
    <Card className="p-4"><div className="mb-3 flex items-center gap-2 font-bold"><ShieldCheck className="text-emerald-600" size={20}/>Privacidade dos comprovantes</div><p className="text-sm leading-6 text-slate-600 dark:text-slate-400">Imagens e PDFs ficam no armazenamento local. Para leitura automática, uma cópia temporária é enviada ao endpoint seguro, que chama o Gemini sem expor a chave no navegador.</p></Card>
    <div><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-400">Aparência</p><div className="grid grid-cols-3 gap-2">{themes.map(({value,label,Icon})=><button key={value} onClick={()=>app.setTheme(value)} className={`flex flex-col items-center gap-2 rounded-2xl border p-4 text-sm font-bold transition ${app.theme===value?'border-teal-600 bg-teal-50 text-teal-800 ring-2 ring-teal-600/10 dark:bg-teal-950/30 dark:text-teal-200':'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}>{React.createElement(Icon,{size:20})}{label}</button>)}</div><p className="mt-2 text-xs text-slate-500">“Sistema” acompanha automaticamente a aparência do seu dispositivo e é o padrão inicial.</p></div>
    <div className="space-y-3"><Button onClick={app.backup} disabled={app.loading} variant="outline" className="w-full justify-start"><HardDrive size={19}/>Backup completo, inclusive comprovantes</Button><label className="flex w-full cursor-pointer items-center gap-2 rounded-xl border border-slate-300 px-4 py-3 font-semibold dark:border-slate-700"><Upload size={19}/>Restaurar backup<input type="file" accept=".json,.irbackup.json" onChange={app.restore} className="hidden"/></label><Button onClick={app.accountantPack} disabled={app.loading} variant="outline" className="w-full justify-start"><Package size={19}/>Gerar pacote do contador ({app.filterYear})</Button></div>
    <Card className="p-4"><div className="flex items-center gap-2 font-bold"><Smartphone size={20}/>Aplicativo instalável</div><p className="mt-2 text-sm text-slate-500">{app.pwa.installed?'O Recibos IR já está instalado.':app.pwa.canInstall?'Você pode instalar o Recibos IR na tela inicial.':'Use o menu do navegador e escolha “Adicionar à tela inicial” se a opção automática não aparecer.'}</p>{app.pwa.canInstall&&<Button onClick={app.pwa.install} className="mt-3 w-full">Instalar aplicativo</Button>}</Card>
    <Button onClick={app.logout} variant="danger" className="w-full">Sair</Button><p className="self-center text-center text-xs text-slate-400">Recibos IR · versão 5.0</p>
  </div></div>;
}
