import React from 'react';
import { HardDrive, Package, ShieldCheck, Smartphone, Upload } from 'lucide-react';
import { Button, Card } from './ui';

export function SettingsScreen({ app, header }) {
  return <div className="pb-12">{header('Configurações')}<div className="space-y-5">
    <Card className="p-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-600 font-black text-white">{app.user.displayName?.[0]||'V'}</div><div><p className="font-bold">{app.isGuest?'Modo visitante':app.user.displayName}</p><p className="text-xs text-slate-500">{app.isGuest?'Dados locais neste dispositivo':app.user.email}</p></div></div></Card>
    <Card className="p-4"><div className="mb-3 flex items-center gap-2 font-bold"><ShieldCheck className="text-emerald-600" size={20}/>Privacidade dos comprovantes</div><p className="text-sm leading-6 text-slate-600 dark:text-slate-400">Imagens e PDFs ficam no armazenamento local. Para leitura automática, uma cópia temporária é enviada ao endpoint seguro, que chama o Gemini sem expor a chave no navegador.</p></Card>
    <div><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-400">Aparência</p><div className="grid grid-cols-3 gap-2">{['light','dark','system'].map((mode)=><button key={mode} onClick={()=>app.setTheme(mode)} className={`rounded-xl border p-3 text-sm font-bold ${app.theme===mode?'border-blue-600 bg-blue-50 text-blue-700 dark:bg-blue-950/30':'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}>{mode==='light'?'Claro':mode==='dark'?'Escuro':'Sistema'}</button>)}</div></div>
    <div className="space-y-3"><Button onClick={app.backup} disabled={app.loading} variant="outline" className="w-full justify-start"><HardDrive size={19}/>Backup completo, inclusive comprovantes</Button><label className="flex w-full cursor-pointer items-center gap-2 rounded-xl border border-slate-300 px-4 py-3 font-semibold dark:border-slate-700"><Upload size={19}/>Restaurar backup<input type="file" accept=".json,.irbackup.json" onChange={app.restore} className="hidden"/></label><Button onClick={app.accountantPack} disabled={app.loading} variant="outline" className="w-full justify-start"><Package size={19}/>Gerar pacote do contador ({app.filterYear})</Button></div>
    <Card className="p-4"><div className="flex items-center gap-2 font-bold"><Smartphone size={20}/>Aplicativo instalável</div><p className="mt-2 text-sm text-slate-500">{app.pwa.installed?'O IR Organiza já está instalado.':app.pwa.canInstall?'Você pode instalar o IR Organiza na tela inicial.':'Use o menu do navegador e escolha “Adicionar à tela inicial” se a opção automática não aparecer.'}</p>{app.pwa.canInstall&&<Button onClick={app.pwa.install} className="mt-3 w-full">Instalar aplicativo</Button>}</Card>
    <Button onClick={app.logout} variant="danger" className="w-full">Sair</Button><p className="text-center text-xs text-slate-400">IR Organiza 4.0</p>
  </div></div>;
}
